name: telecheck-healthcare
services:
  - name: api
    source_dir: /
    github:
      repo: arthurmenson/builder-spark-oasis
      branch: main
      deploy_on_push: true
    run_command: npm start
    build_command: npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: TELNYX_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: TWILIO_ACCOUNT_SID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: TWILIO_AUTH_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET

databases:
  - name: telecheck-db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
    production: false

static_sites:
  - name: frontend
    source_dir: /dist/spa
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    routes:
      - path: /api
        preserve_path_prefix: true
      - path: /
        preserve_path_prefix: true

alerts:
  - rule: CPU_UTILIZATION
    value: 80
  - rule: MEM_UTILIZATION
    value: 80
  - rule: RESTART_COUNT
    value: 10
